### ISSUE TITLE
Can this be compiled for earlier releases of Mac OS X ?

### ISSUE THREAD

**Issue by sandrobilbeisi** [PierreLorenzi/HyperCardPreview#1]
Can this be compiled for earlier releases of Mac OS X ?

( such as 10.10 )

It seems to need the 10.12 SDK for compilation

**Comment by PierreLorenzi** [comment]
As far as I know, the App doesn’t use any critical feature that isn't available on 10.10.

Do you have any issue when compiling?

**Comment by sandrobilbeisi** [comment]
yes, I tried compiling on Mac OS 10.10 with the SDK for 10.10 and 10.11
but not SDK 10.12
it seems that there are unsupported language features ...
such as:
```swift
if let r = resource as? Resource<T>, r.type === type, r.identifier == identifier {
```
```error
HyperCardPreview-master/HyperCardCommon/HyperCardCommon/ResourceSystem.swift:19:52: Boolean condition requires 'where' to separate it from variable binding
```

there are over 100 such errors ...

**Comment by PierreLorenzi** [comment]
Ok, it won't compile because Swift 3 is not available in SDK 10.11. So the compilation is a lost cause. But the application could still run in Mac OS 10.10 because the Swift libraries are embedded.

**Comment by splorp** [comment]
Just to confirm, the current minimum system requirement 10.12, correct?

Perhaps that can be added to the read me file.

**Comment by sandrobilbeisi** [comment]
Can anyone please compile for Mac OS X 10.10 ?

**Comment by PierreLorenzi** [comment]
You're right, I've added the version to the Read Me.

And Sandro, if you download the 1.0 release (in the "1 release" tab), it doesn't work?

**Comment by sandrobilbeisi** [comment]
It doesn't run on Mac OS X 10.10
![screen shot 2017-08-21 at 19 44 21](https://user-images.githubusercontent.com/755824/29531513-3413a20c-86a9-11e7-99f2-dc76f507c2e9.png)
which says :
> **You can’t use this version of the application “HyperCardPreview.app” with this version of OS X.**
> You have OS X 10.10.5. The application requires OS X 10.12 or later.

**Comment by PierreLorenzi** [comment]
We can do a test I you wish, I can send you a 10.10 version to see if it works. It is just a setting to change but I don't know if the app will really work.

**Comment by sandrobilbeisi** [comment]
let's try it !
