### ISSUE TITLE
warning "Cast from '() -> Void' to unrelated type () -> T" in fillMatchingSchema - safe to ignore?

### ISSUE THREAD

**Issue by Jimw338** [PierreLorenzi/HyperCardPreview#11]
I get a warning "Cast from '() -> Void' to unrelated type '() -> T' always fails" at "^^" point in fillMatchingSchema function.

            /* Handle untyped schemas */
            if T.self == Void.self && self.computation == nil {
                
                ^^^self.computeSequenceBy({ () -> Void in return () } as! () -> T)
            }

This doesn't prevent it from compiling or running correctly (I don't think).

**Comment by PierreLorenzi** [comment]
Yes you can ignore it.

**Comment by Jimw338** [comment]
I got the warning to go away by changing it to:
            self.computeSequenceBy({ () -> T in return () as! T })
