### ISSUE TITLE
Missing license information

### ISSUE THREAD

**Issue by hfiguiere** [PierreLorenzi/HyperCardPreview#15]
This git repository doesn't have any licensing information.

**What license is the software released under?** What about the documentation.

This is quite important as this project is a good source of information about HyperCard file format.

Thanks!

**Comment by PierreLorenzi** [comment]
There is no license for this project, nor the documentation. I didn't bother choosing one because the community around HyperCard is very small and there is no money involved. Sorry if that's a trouble.

**Comment by hfiguiere** [comment]
The problem is that without license nobody can legally use the code. Hence I was seeking clarification on that.

**Comment by PierreLorenzi** [comment]
Ok, I'll add one

**Comment by PierreLorenzi** [comment]
Here it is, is it all right for you ? (sorry for the delay)

**Comment by hfiguiere** [comment]
Yes, it make things clear. Thanks !
