### ISSUE TITLE
Export Art

### ISSUE THREAD

**Issue by BenCreating** [PierreLorenzi/HyperCardPreview#5]
The ability to export the art for the cards, backgrounds, and icons would be incredibly valuable to anyone working to port old stacks to newer systems, or wanting to rescue old artwork.

If an export is beyond the scope of this project, just having a way to hide everything but the card or background art so someone can take a screenshot without buttons or fields would be useful.

**Comment by PierreLorenzi** [comment]
Ok, I'll make a new version with what you are suggesting (including the list of the icons).

Would you be interested in global text export? I'm not sure in what format and in how many files the text could be exported.

**Comment by splorp** [comment]
> Would you be interested in global text export? I'm not sure in what format and in how many files the text could be exported.

This would be a very useful feature for me as well.

**Comment by PierreLorenzi** [comment]
Ok then!

**Comment by BenCreating** [comment]
That would be amazing!

Also really useful would be if you could export  a text file with the data you display in the Info tab for buttons and fields, along with the position, size, and id, if possible. That would make it really easy for me to automate the process of porting my stacks.

**Comment by PierreLorenzi** [comment]
I've made a new release  with these changes, HyperCardPreview 1.3.

**Comment by splorp** [comment]
This is great. Thank you!

**Comment by BenCreating** [comment]
Fantastic! Thank you!
