### ISSUE TITLE
FontDescriptor: How to deal with hashValue -> hash(into:) change?  What to do with the hasher parameter?

### ISSUE THREAD

**Issue by Jimw338** [PierreLorenzi/HyperCardPreview#8]
How do I deal with the change from a "simple" hashValue to the newer hashValue(into:hasher hasher) in FontDescriptor?  If I change the declaration (var hashValue) to "func hash(into hasher: inout Hasher) -> Int {", it gets rid of that error (presumably it works as it should, even though it doesn't do anything with the "hasher" parameter.

Even then, it still says the FontDescriptor doesn't conform to the protocol "Hashable" - but doesn't give any (I would suppose helpful) information as to *how*.  I presume there are other protocol functions/variables that have that they added.

Thanks,

**Comment by MaddTheSane** [comment]
The replacement would look something like this:

````
    public func hash(into hasher: inout Hasher) {
        identifier.hash(into: &hasher)
        size.hash(into: &hasher)
        style.hash(into: &hasher)
    }
````

…with `TextStyle` also being `Hashable`.

The easiest way to make `TextStyle` `Hashable` is to change it to an `OptionSet` as I've [done on my fork](https://github.com/MaddTheSane/HyperCardPreview/blob/a00f66fb090413434d2aa9ec4d7c1f646a1de39e/HyperCardCommon/HyperCardCommon/CommonTypes.swift#L136-L338).
