### ISSUE TITLE
NSRect initializer - "cannot type-check in a reasonable time"

### ISSUE THREAD

**Issue by Jimw338** [PierreLorenzi/HyperCardPreview#9]
I managed to compile this with Swift 5 enabled, but got a "cannot type-check in a reasonable time" error with the following NSRect initialization:

// original
return NSRect(x: view.frame.width/2 - initialSize/2,
                         y: view.frame.height/2 - initialSize/2,
                         width: initialSize,
                         height: initialSize)

// I got rid of the error by explicitly type-casting *everything*:

return NSRect(x: (CGFloat) ( ((CGFloat) (view.frame.width/2)) -
                            (CGFloat) (initialSize/2) ),
                        y: (CGFloat) ( ((CGFloat) (view.frame.height/2)) -
                            (CGFloat) (initialSize/2) ),
                        width: initialSize,
                        height: initialSize)

Is there any better way to do this?  (Aside from the fact that I don't see why the first-example *can't* be type-checked, but I suppose there's some "type-checking theory" involving what exactly the type of "view.frame.width" is (as initialSize is an explicit CGFloat).

There's a post somewhere about how the "no implicit type casting" could encourage people to use the "wrong" abstractions simply to avoid the wordiness of explicit casts - say a variable that really should be an Integer, but the programmer declares as a CGFloat because it's used with NSRects and such all over.  Does Swift have a concept of "allowable implicit casts" - where the programmer could explicitly specify sets of casts that would *not* lose any precision (Int -> CGFloat, Float->CGFloat [?], Int -> Double, etc), to alleviate this?  Precision-losing casts would still need to be explicit.

**Comment by PierreLorenzi** [comment]
Why are you using Swift 5? It's still in beta and the program is in Swift 4. I'll do the conversion anyway soon enough.
